notes/urls.py
from django.urls import path

from . import views

app_name="notes"

urlpatterns=[
    path('',views.index,name="index"),
    path('addNote/',views.addNote,name="addNote"),
]

planner/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/',include("tasks.urls")),
    path('notes/',include("notes.urls")),
    path('',include("tasks.urls"))
]

tasks/urls.py
from django.urls import path

from . import views

app_name="tasks"

urlpatterns = [
    path('',views.index,name="index"),
    path('home/',views.home,name="home"),
    path('<int:task_id>/',views.task_view,name="task_view"),
    path('delete/<int:task_id>/',views.delete,name="delete"),
    path('add/',views.add,name="add"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
    path('register/',views.register,name="register"),
]

notes/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
from tasks.models import User

class Note(models.Model):
    title=models.CharField(max_length=50)
    message=models.CharField(max_length=500)
    datetime=models.DateTimeField()
    owner=models.ForeignKey(User,on_delete=CASCADE,related_name="notes")

tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields import EmailField

# Create your models here.

class User(AbstractUser):
    pass

# class User(models.Model):
#     username=models.CharField(max_length=20,unique=True)
#     password=models.CharField(max_length=20)
#     email=models.EmailField()

#     def create_user(self, username,password,email):
#         self.username=username
#         self.password=password
#         self.email=email
#         return self
    # pass

class task(models.Model):
    sdate=models.DateField()
    stime=models.TimeField()
    edate=models.DateField()
    etime=models.TimeField()
    title=models.CharField(max_length=64)
    description=models.CharField(max_length=400)
    owner=models.ForeignKey(User,on_delete=CASCADE,related_name="tasks")

    def create_task(self,sdate,edate,stime,etime,title,des):
        self.sdate=sdate
        self.edate=edate
        self.stime=stime
        self.etime=etime
        self.title=title
        self.description=des
        return self


    # username=models.CharField(max_length=20)
    # password=models.CharField(max_length=20)
    # email=models.EmailField(blank=True)
    # tasks = models.ManyToManyField(task, blank=True)

notes/views.py
from django.forms.widgets import Textarea
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
import datetime
from django import forms
from django.urls.base import reverse
from .models import User,Note


class NewNote(forms.Form):
    title=forms.CharField(label="Title",max_length=50,)
    message=forms.CharField(label="Note",widget=Textarea())
    

def index(request):
    return render(request,"notes/index.html")

def addNote(request):
    if request.method == "POST":
        form=NewNote(request.POST)
        if form.is_valid():
            title=form.cleaned_data['title']
            note=form.cleaned_data['message']
            user_id=request.POST['user_id']
            user=User.objects.get(pk=user_id)
            temp=Note(title=title,message=note,datetime=datetime.datetime.now(),owner=user)
            temp.save()
            user.notes.add(temp)
            return HttpResponseRedirect(reverse('notes:index'))
        else:
            return render(request,"notes/add.html",{
                "form":form
            })
    return render(request,"notes/add.html",{
        "form":NewNote()
    })

tasks/views.py
from django.contrib import auth
from django.http.response import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import IntegrityError
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django import forms
from . import util
from .models import User, task
import datetime

def index(request):
    return render(request,"tasks/index.html")

def add(request):
    if request.method == "POST":
        title=request.POST["title"]
        description=request.POST['description']
        if title=="":
            print("Here")
            return render(request,"tasks/add.html",{
                "message":"Title can't be empty"
            })
        sdate=request.POST['sdate']
        edate=request.POST['edate']
        stime=request.POST['stime']
        etime=request.POST['etime']
        user_id=request.POST['user_id']
        owner=User.objects.get(pk=user_id)
        tsk = task(sdate= sdate,edate= edate,stime= stime,etime= etime,title= title,description= description,owner=owner)
        tsk.save()
        owner.tasks.add(tsk)
        return HttpResponseRedirect(reverse('tasks:home'))
    return render(request, "tasks/add.html")

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('tasks:index'))
        else:
            return render(request, "tasks/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "tasks/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('tasks:index'))


def register(request):
    if request.method == "POST":
        uname = request.POST["username"]
        em = request.POST["email"]
        # Ensure password matches confirmation
        pswd = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if pswd != confirmation:
            return render(request, "tasks/register.html", {
                "message": "Passwords must match."
            })
        # Attempt to create new user
        try:
            user = User.objects.create_user(username=uname,password=pswd,email=em)
            user.save()
        except IntegrityError:
            return render(request, "tasks/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("tasks:index"))
    else:
        return render(request, "tasks/register.html")

def task_view(request,task_id):
    # temp=User.objects.get(pk=user_id)
    # tsk=task.objects.get(pk=task_id,owner=temp)
    temp=task.objects.filter(pk=task_id)
    print(temp)
    if len(temp)==0:
        return HttpResponse("<h1>Error 404 Not Found</h1>")
    tsk=task.objects.get(pk=task_id)
    return render(request,"tasks/task.html",{
        "task":tsk
    })

def delete(request,task_id):
    temp=task.objects.filter(pk=task_id)
    print(temp)
    if len(temp)==0:
        return HttpResponse("<h1>Error 404 Not Found</h1>")
    tsk=task.objects.get(pk=task_id)
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(request, username=username,password=password)
        # print(f"Up = {user.password}")
        if user is not None:
            tsk.delete()
            return HttpResponseRedirect(reverse('tasks:home'))
        return render(request,"tasks/delete_conf.html",{
            "message":"Wrong Password",
            "task":tsk
        })
    return render(request,"tasks/delete_conf.html",{
        "task":tsk
    })

def home(request):
    return render(request,"tasks/home.html")

notes/templates/notes/add.html
{% extends "notes/layout.html" %}

{% block head %}
    <style>
        #sbtn{
            background-color: rgb(87, 87, 230);
            color: white;
            border: none;
            border-radius: 4px;
            padding: 8px;
            font-weight: bold;
        }
        #sbtn:hover{
            cursor: pointer;
            background-color: royalblue;
            /* border: 1px solid royalblue; */
        }
    </style>
{% endblock %}

{% block body %}
{% if user.is_authenticated %}
    <div style="padding: 20px;font-family: 'Courier New', Courier, monospace;">
        <div style="border: 1px solid grey;background-color: rgb(232, 232, 253);border-radius: 8px;width: 275px;margin: auto;padding: 10px;">
            <h1 style="text-align: center;">Add New Note</h1>
            <div>
                <form action="{% url 'notes:addNote' %}" method="POST">
                    {% csrf_token %}
                    <div style="display: flex;flex-direction: column ;margin: 5px;padding: 5px;width: 250px;">
                        {{form}}
                    </div>
                    <input type="hidden" name="user_id" value="{{user.id}}">
                    <div style="width: 60px;margin: auto;">
                        <input type="submit" value="Add Note" id="sbtn">
                    </div>
                </form>
            </div>
        </div>
    </div>
        {% else %}
    <strong>Login/register to view</strong>
    {% endif %}
{% endblock %}

notes/templates/notes/index.html
{% extends "notes/layout.html" %}

{% block body %}
    {% if user.is_authenticated %}
        <h1 style="margin: 10px;font-family: 'Times New Roman', Times, serif;">Notes</h1>
        <div style="display: flex; flex-wrap: wrap;">
            {% for note in user.notes.all %}
                <div style="width: 150px;min-height: 100px;border-radius: 8px;text-align: center; background-color: seashell;margin: 10px;padding: 10px;">
                    <h4><strong>{{note.title}}</strong></h4>
                    <p>{{note.message}}</p>
                </div>
            {% empty %}
                No notes.
            {% endfor %}
        </div>
    {% else %}
        <strong>Login/Rigister to view</strong>
    {% endif %}
{% endblock %}

notes/templates/notes/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'notes/styles.css' %}">
    {% block head %}{% endblock %}
    <title>Notes</title>
</head>
<body>
    <header>
        <div style="display: flex;">
            <div class="head">
                <ul>
                    {% if user.is_authenticated %}
                    <a href="{% url 'notes:index' %}"><li>Home</li></a>
                    <a href="{% url 'notes:addNote' %}"><li>Add new note</li></a>
                    <a href="{% url 'tasks:home' %}"><li>Tasks</li></a>
                    <a href="{% url 'tasks:logout' %}"><li>Logout</li></a>
                    {% else %}
                    <a href="{% url 'tasks:login' %}">Login</a>
                    <a href="{% url 'tasks:register' %}">Register</a>
                    {% endif %}
                </ul>
            </div>
            {% if user.is_authenticated %}
                <div style="width: auto;padding: 15px;">
                    <strong>Hello {{user.username}}</strong>
                </div>
            {% endif %}
        </div>
    </header>
    <div>
        {% block body %}
        {% endblock %}
    </div>
</body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/task_landing.html" %}
{% load static %}
{% block body %}
    <h1 style="padding-bottom: 10px;">Add New Task</h1>
    {% if message %}
        <strong>{{message}}</strong>
    {% endif %}
    <form action="{% url 'tasks:add' %}" method="POST">
        {% csrf_token %}
        <!-- <input type="text" placeholder="Name" name="name"> -->
        <!-- <label for="ongoing">Ongoing</label> -->
        <!-- <input type="checkbox" name="ongoing"> -->
        <!-- {% if not ongoing %} -->
            <label for="title">Title: </label>
            <input type="text" name="title">
            <div>
                <textarea name="description" cols="10" rows="4" placeholder="Description"></textarea>
            </div>
            <div style="display: flex;flex-wrap: wrap;">
                <div style="margin: 5px;">
                    <label for="sdate">Start Date</label>
                    <input type="date" placeholder="Start Date" name="sdate">
                </div>
                <div style="margin: 5px;">
                    <label for="stime">Start Time</label>
                    <input type="time" placeholder="Start Time" name="stime">
                </div>
                <div style="margin: 5px;">
                    <label for="edate">End Date</label>
                    <input type="date" placeholder="End Date" name="edate">
                </div>
                <div style="margin: 5px;">
                    <label for="etime">End Time</label>
                    <input type="time" placeholder="End Time" name="etime">
                </div>
            </div>
            <input type="hidden" value="{{user.id}}" name="user_id">
        <!-- {% endif %} -->
        <!-- <label for="end">End</label>
        <input type="datetime-local" placeholder="End" name="end"> -->
        <div style="width: 90%;padding: 20px;">
            <input type="submit" style="float: right;">
        </div>
    </form>

{% endblock %}

tasks/templates/tasks/delete_conf.html
{% extends "tasks/layout.html" %}

{% block body %}
    {% if user.is_authenticated and task.owner.id == user.id %}
    <h3 style="text-align: center;justify-content: center;color: red;">Enter password to delete "{{task.title}}"?</h3>
    <div class="container" style="width: 40%;margin: auto;">
        {% if message %}
        <strong>{{message}}</strong>
        {% endif %}
            <div>
                <!-- <input type="hidden" name=""> -->
                <form action="{% url 'tasks:delete' task.id %}" method="POST" style="align-items: center;">
                    {% csrf_token %}
                    <div style="padding: 10px;">
                        <input type="password" name="password" placeholder="Password">
                    </div>
                    <input type="hidden" name="username" value="{{user.username}}">
                    <div>
                        <input type="submit" value="Submit" style="margin: auto 71px;">
                    </div>
                </form>
                <div>
                    <a href="{% url 'tasks:home' %}" style="padding: 3px 0;align-items: center;margin: 10px 71px;">Cancel</a>
                </div>
            </div>
        </div>
    {% else %}
        <h1 style="color: red;">Access Denied</h1>
    {% endif %}
{% endblock %}

tasks/templates/tasks/home.html
{% extends "tasks/task_landing.html" %}

{% block body %}
    {% if user.is_authenticated %}

        <div class="row">
            <h1 style="padding: 20px;">Tasks</h1>
        </div>
        <div>
            <ol>
                {% for task in user.tasks.all %}
                    <li style="padding: 5px;"><a href="{% url 'tasks:task_view' task.id %}">{{task.title}}</a> : From {{task.sdate}} at {{task.stime}}</li>
                {% empty %}
                    <li>No Tasks</li>
                {% endfor %}
            </ol>
        </div>
    {% else %}
        <span>Login to view your tasks</span>
    {% endif %}
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    {% if user.is_authenticated %}

        <div class="row">
            <h1 style="padding: 20px;">Tasks</h1>
        </div>
        <div>
            <ol>
                {% for task in user.tasks.all %}
                    <li style="padding: 5px;"><a href="{% url 'task_view' task.id %}">{{task.title}}</a> : From {{task.sdate}} at {{task.stime}}</li>
                {% empty %}
                    <li>No Tasks</li>
                {% endfor %}
            </ol>
        </div>
    {% else %}
        <span>Login to view your tasks</span>
    {% endif %}
{% endblock %}

tasks/templates/tasks/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Planner{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'tasks/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3 col-sm-4">
                <h2>Planner</h2>
                {% if user.is_authenticated %}
                    <span>Signed in as <strong>{{ user.username }}</strong></span>
                    <div><a href="{% url 'index' %}">Home</a></div>
                    <div><a href="{% url 'add'%}">Add New Task</a></div>
                    <div><a href="{% url 'logout' %}">Logout</a></div>
                {% else %}
                    <div><a href="{% url 'login' %}">Login</a></div>
                    <div><a href="{% url 'register' %}">Register</a></div>
                {% endif %}
            </div>
            <div class="main col-lg-10 col-md-9 col-sm-8">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

tasks/templates/tasks/login.html
{% extends "tasks/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'tasks:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'tasks:register' %}">Register here.</a>

{% endblock %}

tasks/templates/tasks/register.html
{% extends "tasks/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'tasks:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'tasks:login' %}">Log In here.</a>

{% endblock %}

tasks/templates/tasks/task.html
{% extends "tasks/layout.html" %}

{% block body %}
    {% if user.is_authenticated and task.owner.id == user.id %}
    <div style="padding-left: 10px;">
        <h1>{{task.title}}</h1>
        <div class="row">
            <div class="col-lg-6">
                <div>
                    <strong>Start Date:</strong> {{task.sdate}}
                </div>
                <div>
                    <strong>Start Time:</strong> {{task.stime}}
                </div>
            </div>
            <div class="col-lg-6">
                <div>
                    <strong>End Date:</strong> {{task.edate}}
                </div>
                <div>
                    <strong>End Time:</strong> {{task.etime}}
                </div>
            </div>
        </div>
        <div style="padding-top: 10px;">
            <p><strong>Description:</strong> {{task.description}}</p>
        </div>
        <a href="{% url 'tasks:delete' task.id %}" style="float: right;margin-right: 20px;">Delete</a>
        <a href="{% url 'tasks:home' %}">Go back</a>
    </div>
        {% else %}
        <h1 style="color: red;">Access Denied</h1>
        {% endif %}
{% endblock %}

tasks/templates/tasks/task_landing.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Planner{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'tasks/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3 col-sm-4">
                <h2>Planner</h2>
                {% if user.is_authenticated %}
                    <span>Signed in as <strong>{{ user.username }}</strong></span>
                    <div><a href="{% url 'tasks:home' %}">Home</a></div>
                    <div><a href="{% url 'tasks:add'%}">Add New Task</a></div>
                    <div><a href="{% url 'notes:index'%}">Notes</a></div>
                    <div><a href="{% url 'tasks:logout' %}">Logout</a></div>
                {% else %}
                    <div><a href="{% url 'tasks:login' %}">Login</a></div>
                    <div><a href="{% url 'tasks:register' %}">Register</a></div>
                {% endif %}
            </div>
            <div class="main col-lg-10 col-md-9 col-sm-8">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>